export {default as Hero} from './home/Hero'
export {default as Facilities} from './home/Facilities'
export {default as About} from './home/About'
export {default as Service} from './home/Service'
export {default as WhyChoose} from './home/WhyChoose'

//common
export {default as FaqAndForm} from './common/FaqAndForm'
export {default as BrandSlider} from './common/BrandSlider'
export {default as Appointment} from './common/Appointment'
export {default as Testimonial} from './common/Testimonial'
export {default as FeaturedHeatingServices} from './common/FeaturedHeatingServices'
export {default as PopularService} from './common/PopularService'
export {default as HighlySkilled} from './common/HighlySkilled'
export {default as Locations} from './common/Locations'
export {default as Different} from './common/Different'
export {default as CertificationSlider} from './common/CertificationSlider'
export {default as FeaturedCoolingServices} from './common/FeaturedCoolingServices'
export {default as BrandDetails} from './common/BrandDetails'